"use strict";
let age = 25;
console.log(age);
let person = "John Doe";
console.log(person);
let isDone = true;
console.log(isDone);
let nothing = null;
console.log(nothing);
let notDefined = undefined;
console.log(notDefined);
