var age = 25;
console.log(age);
var person = "John Doe";
console.log(person);
var isDone = true;
console.log(isDone);
var nothing = null;
console.log(nothing);
var notDefined = undefined;
console.log(notDefined);
var bigNumber = BigInt(8901234567890);
console.log(bigNumber);
